---
title: Nofio Cydamserol
hero_image: images/synchronised-swimming.png
theme: red
description: Cyfle i raglenni cyfres o symudiadau nofio cydamserol.
original_url: https://codeclubprojects.org/en-GB/scratch/synchronised-swimming
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Cyflwyniad
- title: "Nofio i'r Chwith ac i'r Dde"
- title: Newid gwisg
- title: "Creu'r tîm"
- title: Cerddoriaeth!
- title: "Rhaglenni'r drefn"
- title: 'Her: Codio dy drefn dy hunan'
- title: 'Her: Newid y tîm'
site_areas: projects